apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpc-ui
  labels:
    app: gpc-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpc-ui
  template:
    metadata:
      labels:
        app: gpc-ui
    spec:
      containers:
      - name: gpc-ui
        image: foxchin/gpc-ui:20250804.1
        ports:
        - containerPort: 3000
        env:
        - name: NEXTAUTH_URL
          value: "https://gpc.digitalworks.mn"
        - name: NEXTAUTH_SECRET
          value: ""
        - name: BACKEND_BASE_URL
          value: "http://103.229.178.13:9001"
        - name: DEPRECIATED_BACKEND
          value: "http://103.229.178.13:9001"
        - name: COMPANYID
          value: "REDACTED"
        - name: AZURE_AD_CLIENT_ID
          value: "REDACTED"
        - name: AZURE_AD_CLIENT_SECRET
          value: "REDACTED"
        - name: AZURE_AD_TENANT_ID
          value: "REDACTED"
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: gpc-ui
spec:
  selector:
    app: gpc-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
