apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  redis.conf: |
    maxmemory 256mb
    maxmemory-policy allkeys-lru
    timeout 0
    tcp-keepalive 300
    databases 16
    save 900 1
    save 300 10
    save 60 10000
    stop-writes-on-bgsave-error yes
    rdbcompression yes
    rdbchecksum yes
    dbfilename dump.rdb
    dir /data
    appendonly yes
    appendfilename "appendonly.aof"
    appendfsync everysec
    requirepass green

---
# Redis Deployment with Custom Config
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-configured
  labels:
    app: redis-configured
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-configured
  template:
    metadata:
      labels:
        app: redis-configured
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        command:
        - redis-server
        - /etc/redis/redis.conf
        volumeMounts:
        - name: redis-data
          mountPath: /data
        - name: redis-config
          mountPath: /etc/redis
      volumes:
      - name: redis-data
        emptyDir: {}
      - name: redis-config
        configMap:
          name: redis-config

---
# Redis Service for Configured Version
apiVersion: v1
kind: Service
metadata:
  name: redis-configured-service
  labels:
    app: redis-configured
spec:
  selector:
    app: redis-configured
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
  type: ClusterIP

---
# Redis Service for Configured Version
apiVersion: v1
kind: Service
metadata:
  name: redis-configured-service
  labels:
    app: redis-configured
spec:
  selector:
    app: redis-configured
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
  type: ClusterIP

---
# Redis Service for Configured Version
apiVersion: v1
kind: Service
metadata:
  name: redis-configured-service-nodeport
  labels:
    app: redis-configured
spec:
  selector:
    app: redis-configured
  ports:
  - protocol: TCP
    nodePort: 30379
    port: 6379
    targetPort: 6379
  type: NodePort
