apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: site-monitor
  name: site-monitor
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: site-monitor
  template:
    metadata:
      labels:
        io.kompose.service: site-monitor
    spec:
      containers:
        - name: site-monitor
          image: foxchin/site-monitor:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: site-monitor
  name: site-monitor
  namespace: default
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 5000
  selector:
    io.kompose.service: site-monitor
  type: ClusterIP
